"""create_api_user_table

Revision ID: 8ab361bce1ec
Revises: cbcd0d416fee
Create Date: 2026-05-19 10:21:29.679645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8ab361bce1ec'
down_revision: Union[str, Sequence[str], None] = 'cbcd0d416fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_user',
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_user_api_key'), 'api_user', ['api_key'], unique=True)
    op.create_index(op.f('ix_api_user_email'), 'api_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_user_email'), table_name='api_user')
    op.drop_index(op.f('ix_api_user_api_key'), table_name='api_user')
    op.drop_table('api_user')
    # ### end Alembic commands ###
