"""add_api_key_table

Revision ID: b4a39c468953
Revises: f5c45ea89ff5
Create Date: 2026-07-01 18:43:46.057541

"""
import hashlib
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b4a39c468953'
down_revision: Union[str, Sequence[str], None] = 'f5c45ea89ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['api_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_key_hash'), 'api_key', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_key_user_id'), 'api_key', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Migra las api_key existentes de api_user (una por usuario) como keys "legacy",
    # ya hasheadas, para no cortar el acceso de integraciones vigentes.
    bind = op.get_bind()
    api_user = sa.table("api_user", sa.column("id"), sa.column("api_key"))
    api_key = sa.table(
        "api_key",
        sa.column("user_id"), sa.column("name"), sa.column("key_hash"),
        sa.column("key_prefix"), sa.column("is_active"), sa.column("created_at"),
    )
    now = datetime.now()
    for user_id, key in bind.execute(sa.select(api_user.c.id, api_user.c.api_key)).fetchall():
        bind.execute(
            api_key.insert().values(
                user_id=user_id,
                name="legacy",
                key_hash=hashlib.sha256(key.encode()).hexdigest(),
                key_prefix=key[:8],
                is_active=True,
                created_at=now,
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_key_user_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_key_hash'), table_name='api_key')
    op.drop_table('api_key')
    # ### end Alembic commands ###
