"""add published_date to noticia

Revision ID: cbcd0d416fee
Revises: aaf1d98822c0
Create Date: 2026-05-18 16:41:28.242851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcd0d416fee'
down_revision: Union[str, Sequence[str], None] = 'aaf1d98822c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('noticia', sa.Column('published_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_noticia_published_date'), 'noticia', ['published_date'], unique=False)

    # Backfill desde date_preview — solo filas con formato válido DD/MM/YYYY
    # (valida que el segundo componente sea mes 1-12 para descartar MM/DD/YYYY)
    op.execute("""
        UPDATE noticia
        SET published_date = TO_DATE(date_preview, 'DD/MM/YYYY')
        WHERE date_preview ~ '^[0-9]{2}/[0-9]{2}/[0-9]{4}$'
          AND SPLIT_PART(date_preview, '/', 2)::int BETWEEN 1 AND 12
    """)
    op.execute("""
        UPDATE noticia
        SET published_date = TO_DATE(date_preview, 'DD-MM-YYYY')
        WHERE date_preview ~ '^[0-9]{2}-[0-9]{2}-[0-9]{4}$'
          AND SPLIT_PART(date_preview, '-', 2)::int BETWEEN 1 AND 12
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_noticia_published_date'), table_name='noticia')
    op.drop_column('noticia', 'published_date')
    # ### end Alembic commands ###
